env:
  es6: false
  browser: true
  amd: true

rules:
  block-spacing: ["error"]
  brace-style: ["error"]
  comma-dangle: ["error", "never"]
  comma-spacing: ["error"]
  eol-last: ["error"]
  indent: ["error", 4, { "SwitchCase": 1 }]
  keyword-spacing: ["error"]
  line-comment-position: ["off"]
  max-statements-per-line: ["error"]
  no-empty: ["error"]
  no-extra-semi: ["error"]
  no-floating-decimal: ["error"]
  no-multi-spaces: ["error"]
  no-multiple-empty-lines: ["error", { "max": 1 }]
  no-trailing-spaces: ["error"]
  no-void: ["off"]
  one-var: ["error", "never"]
  padding-line-between-statements: ["off"]
  semi: ["off"]
  space-before-blocks: ["error"]
  yoda: ["off"]
